#!/bin/bash
#Define dirs
installDir="/opt/protoDisplay"
binDir="/usr/local/bin/"
serviceDir="/etc/systemd/system/"

#make /opt dir
mkdir $installDir
sudo chmod 777 $installDir

#copy program files to the opt dir
cp -a venv $installDir
cp -a lib $installDir
cp -a pic $installDir
cp -a Font.ttc $installDir
cp -a proto.py $installDir
cp -a clearDisplay.py $installDir
cp -a protoDisplay $installDir
cp -a clearDisplay $installDir
cp -a uninstall $installDir
cp -a clearDisplay $installDir

#symlink to local bin
sudo ln -sf $installDir"/protoDisplay" $binDir
sudo ln -sf $installDir"/clearDisplay" $binDir

#copy service unit files
cp -a protoDisplay.service $serviceDir
cp -a protoDisplay.timer $serviceDir
cp -a clearDisplay.service $serviceDir

#reload systemd configuration
sudo systemctl daemon-reload

#start service/timer
sudo systemctl start protoDisplay.service
sudo systemctl enable protoDisplay.service
sudo systemctl start protoDisplay.timer
sudo systemctl enable protoDisplay.timer
sudo systemctl start clearDisplay.service
sudo systemctl enable clearDisplay.service
